// <auto-generated />
using System;
using FitnessDiary.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FitnessDiary.Migrations
{
    [DbContext(typeof(SQLServerContext))]
    [Migration("20240821023504_exercicioTreinos")]
    partial class exercicioTreinos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FitnessDiary.Entidades.CategoriaExercicio", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCategoria"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("IdCategoria");

                    b.ToTable("CategoriaExercicio");
                });

            modelBuilder.Entity("FitnessDiary.Entidades.Exercicio", b =>
                {
                    b.Property<int>("IdExercicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdExercicio"));

                    b.Property<int>("IdGrupoMuscular")
                        .HasColumnType("int");

                    b.Property<int>("IdTreino")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<double>("Peso")
                        .HasColumnType("float");

                    b.Property<string>("Repeticoes")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Series")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdExercicio");

                    b.HasIndex("IdGrupoMuscular");

                    b.HasIndex("IdTreino");

                    b.ToTable("Exercicio");
                });

            modelBuilder.Entity("FitnessDiary.Entidades.GrupoMuscular", b =>
                {
                    b.Property<int>("IdGrupoMuscular")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdGrupoMuscular"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("IdGrupoMuscular");

                    b.ToTable("GrupoMuscular");
                });

            modelBuilder.Entity("FitnessDiary.Entidades.Treino", b =>
                {
                    b.Property<int>("IdTreino")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTreino"));

                    b.Property<double>("CaloriasQueimadas")
                        .HasColumnType("float");

                    b.Property<string>("Duracao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("IdTreino");

                    b.HasIndex("IdCategoria");

                    b.ToTable("Treino");
                });

            modelBuilder.Entity("FitnessDiary.Entidades.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<double?>("Altura")
                        .HasColumnType("float");

                    b.Property<DateTime>("DtaNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NomeDoMeio")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NomeImagem")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PathImagem")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<double?>("Peso")
                        .HasColumnType("float");

                    b.Property<string>("PrimeiroNome")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("FitnessDiary.Entidades.Exercicio", b =>
                {
                    b.HasOne("FitnessDiary.Entidades.GrupoMuscular", "GrupoMuscular")
                        .WithMany("Exercicios")
                        .HasForeignKey("IdGrupoMuscular")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitnessDiary.Entidades.Treino", "Treino")
                        .WithMany("Exercicios")
                        .HasForeignKey("IdTreino")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GrupoMuscular");

                    b.Navigation("Treino");
                });

            modelBuilder.Entity("FitnessDiary.Entidades.Treino", b =>
                {
                    b.HasOne("FitnessDiary.Entidades.CategoriaExercicio", "Categoria")
                        .WithMany("Treinos")
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("FitnessDiary.Entidades.CategoriaExercicio", b =>
                {
                    b.Navigation("Treinos");
                });

            modelBuilder.Entity("FitnessDiary.Entidades.GrupoMuscular", b =>
                {
                    b.Navigation("Exercicios");
                });

            modelBuilder.Entity("FitnessDiary.Entidades.Treino", b =>
                {
                    b.Navigation("Exercicios");
                });
#pragma warning restore 612, 618
        }
    }
}
